image: node

before_script:
  - npm install
  - npm install pm2 -g
  - npm run build

cache:
  paths:
    - node_modules/

artifacts:
  paths:
    - .nuxt

pages:
  script:
    - cd /home/ubuntu/avant
    - pm2 start ecosystem.config.js --only nuxt-prod
  only:
    - master
